# crew/tasks.py
from crewai import Task
from crew.agents import (
    classifier_agent,
    clinical_analyst_agent,
    recommendations_agent,
    report_agent
)
from tools.classifier_tool import classify_brain_mri
from tools.medical_knowledge_tool import search_medical_knowledge
from datetime import datetime


def create_classification_task(image_path: str) -> Task:
    return Task(
        description=f"""Analyze the MRI image to detect brain tumors.
Use the classify_brain_mri tool with the path: {image_path}

You must return EXACTLY these three lines (nothing else):
Diagnosis: Tumor detected / No tumor detected
Confidence: XX.X%
Tumor probability: XX.X%""",
        agent=classifier_agent,
        tools=[classify_brain_mri],
        expected_output="Three lines: Diagnosis, Confidence, and Tumor probability"
    )


def create_clinical_analysis_task(classification_result: str) -> Task:
    return Task(
        description=f"""Perform comprehensive clinical analysis based on previous results:

CLASSIFICATION:
{classification_result}

Use search_medical_knowledge to enhance your analysis.
Return ONLY in English and in this format:

Probable type: Glioblastoma / Meningioma / Astrocytoma / etc.
WHO Grade: I / II / III / IV / Undetermined
Prognosis without treatment: median survival X months""",
        agent=clinical_analyst_agent,
        tools=[search_medical_knowledge],
        expected_output="Clinical analysis in 3 lines: Probable type, WHO Grade, Prognosis"
    )


def create_recommendations_task(clinical_result: str) -> Task:
    return Task(
        description=f"""Provide appropriate clinical recommendations.

CLINICAL ANALYSIS:
{clinical_result}

Use search_medical_knowledge if needed.
Return ONLY:

Urgency: Immediate / Within 48h / Planned within 2 weeks
Next step: Follow-up MRI / Neurosurgical consultation / Biopsy / etc.
Standard treatment: Surgery + radiotherapy + temozolomide / etc.""",
        agent=recommendations_agent,
        tools=[search_medical_knowledge],
        expected_output="Recommendations in 3 lines: Urgency, Next step, Standard treatment"
    )


def create_report_task(
    classification_result: str,
    clinical_result: str,
    recommendations_result: str
) -> Task:
    return Task(
        description=f"""Write the final comprehensive medical report following EXACTLY this structure:

═══════════════════════════════════════
BRAIN MRI ANALYSIS REPORT – BrainTumorAISystem
═══════════════════════════════════════

{classification_result}

CLINICAL ANALYSIS:
{clinical_result}

RECOMMENDATIONS:
{recommendations_result}

═══════════════════════════════════════
Report date: {datetime.now().strftime("%d/%m/%Y %H:%M")}
Generated by: BrainTumorAISystem Multi-Agent System
═══════════════════════════════════════""",
        agent=report_agent,
        expected_output="Complete and structured medical report with headers and separators"
    )